"""Initial migration

Revision ID: 89f44bd7dc22
Revises: 
Create Date: 2024-09-03 11:22:31.285866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f44bd7dc22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ori_name', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('poster', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('creators', sa.Text(), nullable=False),
    sa.Column('director', sa.Text(), nullable=False),
    sa.Column('actors', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rating_imdb', sa.Float(), nullable=True),
    sa.Column('rating_kinopoisk', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_id'), 'shots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
